import { css } from '@emotion/css';
import { GrafanaTheme2 } from '@grafana/data';

export const getKioskOverlayStyles = (theme: GrafanaTheme2) => ({
  backdrop: css({
    position: 'fixed',
    inset: 0,
    zIndex: 100000,
    background: theme.colors.background.canvas,
    color: theme.colors.text.primary,
    overflow: 'auto',
  }),
  container: css({
    maxWidth: 1200,
    width: '100%',
    margin: '0 auto',
    padding: theme.spacing(0, 3, 4),
    display: 'flex',
    flexDirection: 'column',
    gap: theme.spacing(3),
    [theme.breakpoints.down('sm')]: { padding: theme.spacing(0, 2, 3) },
  }),
  header: css({
    position: 'sticky',
    top: 0,
    zIndex: 1,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: theme.spacing(2),
    padding: theme.spacing(3, 0),
    background: theme.colors.background.canvas,
    borderBottom: `1px solid ${theme.colors.border.weak}`,
    [theme.breakpoints.down('sm')]: { alignItems: 'flex-start', padding: theme.spacing(2, 0) },
  }),
  titleGroup: css({ display: 'flex', flexDirection: 'column', gap: theme.spacing(1) }),
  title: css({
    display: 'flex',
    alignItems: 'center',
    gap: theme.spacing(1),
    fontSize: theme.typography.h3.fontSize,
    fontWeight: theme.typography.fontWeightMedium,
    margin: 0,
  }),
  subtitle: css({ fontSize: theme.typography.body.fontSize, color: theme.colors.text.secondary, margin: 0 }),
  banner: css({
    padding: theme.spacing(3),
    borderRadius: theme.shape.radius.default,
    border: `1px solid ${theme.colors.border.weak}`,
    background: theme.colors.background.primary,
    overflowWrap: 'anywhere',
    '& img': { maxWidth: '100%', height: 'auto' },
    '& a': { color: theme.colors.text.link, textDecoration: 'underline' },
    '& p:last-child': { marginBottom: 0 },
  }),
  learningBanner: css({
    display: 'flex',
    alignItems: 'center',
    gap: theme.spacing(3),
    padding: theme.spacing(4),
    background: theme.colors.background.primary,
    border: `1px solid ${theme.colors.border.weak}`,
    borderLeft: `4px solid ${theme.colors.primary.main}`,
    borderRadius: theme.shape.radius.default,
    [theme.breakpoints.down('sm')]: { alignItems: 'flex-start', gap: theme.spacing(2), padding: theme.spacing(2.5) },
  }),
  learningMark: css({
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    width: 72,
    height: 72,
    borderRadius: theme.shape.radius.default,
    color: theme.colors.primary.text,
    background: theme.colors.primary.transparent,
    [theme.breakpoints.down('sm')]: { display: 'none' },
  }),
  learningCopy: css({ display: 'flex', flexDirection: 'column', gap: theme.spacing(1) }),
  learningEyebrow: css({
    color: theme.colors.primary.text,
    fontSize: theme.typography.bodySmall.fontSize,
    fontWeight: theme.typography.fontWeightMedium,
  }),
  learningTitle: css({
    margin: 0,
    fontSize: theme.typography.h3.fontSize,
    fontWeight: theme.typography.fontWeightMedium,
  }),
  learningDescription: css({ margin: 0, color: theme.colors.text.secondary, fontSize: theme.typography.body.fontSize }),
  closeButton: css({ flexShrink: 0, whiteSpace: 'nowrap' }),
  grid: css({
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(min(100%, 300px), 1fr))',
    gap: theme.spacing(2),
  }),
  loading: css({ padding: theme.spacing(6), textAlign: 'center', color: theme.colors.text.secondary }),
  tile: css({
    display: 'flex',
    flexDirection: 'column',
    gap: theme.spacing(2),
    padding: theme.spacing(2.5),
    borderRadius: theme.shape.radius.default,
    border: `1px solid ${theme.colors.border.weak}`,
    background: theme.colors.background.primary,
    color: theme.colors.text.primary,
    font: 'inherit',
    textAlign: 'left',
    cursor: 'pointer',
    overflowWrap: 'anywhere',
    '&:hover': { background: theme.colors.action.hover, borderColor: theme.colors.border.medium },
    '&:focus-visible': { outline: `2px solid ${theme.colors.primary.main}`, outlineOffset: 2 },
  }),
  tileIconRow: css({ display: 'flex', alignItems: 'center', justifyContent: 'space-between', width: '100%' }),
  tileIcon: css({ color: theme.colors.text.secondary }),
  tileBadge: css({
    padding: theme.spacing(0.25, 1),
    borderRadius: theme.shape.radius.default,
    background: theme.colors.background.secondary,
    color: theme.colors.text.secondary,
    fontSize: theme.typography.bodySmall.fontSize,
  }),
  tileTitle: css({ fontSize: theme.typography.h5.fontSize, fontWeight: theme.typography.fontWeightMedium, margin: 0 }),
  tileDescription: css({
    fontSize: theme.typography.bodySmall.fontSize,
    color: theme.colors.text.secondary,
    margin: 0,
  }),
  tileArrow: css({
    display: 'flex',
    alignItems: 'center',
    gap: theme.spacing(1),
    color: theme.colors.text.link,
    fontSize: theme.typography.bodySmall.fontSize,
    marginTop: 'auto',
    paddingTop: theme.spacing(1),
  }),
  warning: css({
    padding: theme.spacing(2),
    borderRadius: theme.shape.radius.default,
    background: theme.colors.warning.transparent,
    border: `1px solid ${theme.colors.warning.border}`,
    color: theme.colors.text.primary,
    fontSize: theme.typography.bodySmall.fontSize,
  }),
});
