name: Latest Grafana API compatibility check
on: [pull_request]

jobs:
  compatibilitycheck:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Read repository contents for compatibility check
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - name: Setup Node.js environment
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version: '24'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build plugin
        run: npm run build
      - name: Find module.ts or module.tsx
        id: find-module-ts
        run: >-
          MODULETS="$(find ./src -type f \( -name "module.ts" -o -name
          "module.tsx" \))"

          echo "modulets=${MODULETS}" >> $GITHUB_OUTPUT
      - name: Compatibility check
        uses: grafana/plugin-actions/is-compatible@fb5e15c76707026bf6171d6808527fa2d838b781 # main
        with:
          module: ${{ steps.find-module-ts.outputs.modulets }}
          comment-pr: no
          fail-if-incompatible: yes
