name: Latest Grafana API compatibility check
on: [pull_request]

jobs:
  compatibilitycheck:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Read repository contents for compatibility check
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          persist-credentials: false
      - name: Setup Node.js environment
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: '24'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build plugin
        run: npm run build
      - name: Find module.ts or module.tsx
        id: find-module-ts
        run: >-
          MODULETS="$(find ./src -type f \( -name "module.ts" -o -name
          "module.tsx" \))"

          echo "modulets=${MODULETS}" >> $GITHUB_OUTPUT
      - name: Compatibility check
        uses: grafana/plugin-actions/is-compatible@d0240a622e21c5321b35732d4cee961a386d2d92 # main
        with:
          module: ${{ steps.find-module-ts.outputs.modulets }}
          comment-pr: no
          fail-if-incompatible: yes
